version: '3.7'

services:
  vault:
    image: vault
    depends_on:
      - consul-leader
    ports:
      - "8200:8200"
    volumes:
      consul-data-leader:/consul/data
    cap_add:
      - IPC_LOCK
    command: server -config=/config/vault.hcl
    networks:
      - vault-private

  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - vault-private
      - swarmlet-network
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:consul.${DOMAIN}
        - traefik.enable=true
        - traefik.port=8500
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.usersFile=/basicAuth/security.htpasswd

  consul-replica:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - vault-private
    deploy:
      replicas: ${CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id
 
  # certdumper:
  #   image: svendowideit/traefik-certdumper:latest
  #   environment:
  #     - CERTDUMPER_MODE=consul
  #     - CERTDUMPER_CONSUL_ADDR=consul-leader:8500
  #   volumes:
  #     - traefik-certs:/traefik/ssl
  #   networks:
  #     - vault-private
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #       delay: 60s

volumes:
  consul-data-leader:
  consul-data-replica:
  # traefik-certs:
  #   external: true

networks:
  vault-private:
  swarmlet-network:
    external: true
  traefik-public:
    external: true
